FROM centos:7.3.1611
MAINTAINER Michael Reuter <mareuter@lsst.org>

RUN yum install -y \
  bzip2 \
  git \
  boost-python \
  mesa-libGL-devel \
  libXrender-devel \
  libSM-devel \
  libICE-devel \
  xorg-x11-fonts-100dpi \
  xorg-x11-fonts-Type1 \
  xorg-x11-fonts-ISO8859-1-100dpi \
  xorg-x11-fonts-misc \
  gnu-free-sans-fonts \
  liberation-*-fonts \
  dejavu-*-fonts \
  open-sans-fonts
