#!/usr/bin/env python
import argparse

from lsst.sims.ocs.database import SocsDatabase
from lsst.sims.ocs.setup import write_file_config

def main(args):
    db = SocsDatabase(sqlite_save_path=args.save_dir,
                      session_id_start=args.session_id_start,
                      sqlite_session_save_path=args.session_save_dir)

    args.type = "sqlite"
    write_file_config(args)
    db.create_db()


if __name__ == '__main__':
    description = ["This script creates session database for version 4 of"]
    description.append("the Operations Simulator. You need to provide a directory")
    description.append("to save it and the run databases, otherwise the script will ")
    description.append("save the files in the working directory.")

    parser = argparse.ArgumentParser(usage="manage_db [options]",
                                     description=" ".join(description),
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument("-s", "--session-id-start", dest="session_id_start",
                        help="Set the session Id to start new runs counting from.")
    parser.add_argument("--save-dir", dest="save_dir", help="A directory to save the all SQLite output "
                        "from the simulator including the session tracking database.")
    parser.add_argument("--session-save-dir", dest="session_save_dir", help="A directory to save the SQLite "
                        "session tracking database only.")

    args = parser.parse_args()
    main(args)
