FROM centos:7.3.1611
MAINTAINER Michael Reuter <mareuter@lsst.org>

RUN yum install -y \
    bzip2 \
    git \
    boost-python \
    mesa-libGL-devel \
    libXrender-devel \
    libSM-devel \
    libICE-devel \
    xorg-x11-fonts-100dpi \
    xorg-x11-fonts-Type1 \
    xorg-x11-fonts-ISO8859-1-100dpi \
    xorg-x11-fonts-misc \
    gnu-free-sans-fonts \
    liberation-*-fonts \
    dejavu-*-fonts \
    open-sans-fonts \
    bison \
    curl \
    blas \
    bzip2-devel \
    flex \
    fontconfig \
    freetype-devel \
    gcc-c++ \
    gcc-gfortran \
    libuuid-devel \
    libXext \
    libXrender \
    libXt-devel \
    make \
    openssl-devel \
    patch perl \
    readline-devel \
    tar zlib-devel \
    ncurses-devel \
    cmake \
    glib2-devel \
    java-1.8.0-openjdk \
    gettext \
    perl-ExtUtils-MakeMaker \
    which && \
    yum clean all
